---
title: "Une part des salaires dans la VA élevée en 2025 en France"
subtitle: "*Historique des modifications*"
toc-title: "*Historique des modifications*"
date-modified: now
authors-title: "Auteur"
format: 
  wp-html:
    appendix-cite-as: false
    number-sections: false
---

## 29/05/2026

-   📥 Mise à jour des données, T1 2026 détaillés (et équivalent en Europe) intégrés. Les autres pays seront progressivement mis à jour en fonction des disponibilités des données.

## 29/11/2025

-   🖌️ ajout de la référence à Sicsic 2018

## 26/11/2025

-   🖌️ Corrections mineures, réorganisation du site.
-   📥 Mise à jour des données.

## 23/11/2025

-   ⚙️ la correction par le revenu mixte pour les non salariés est maintenant la correction des salaires de référence.
-   🖌️ 🖌️ ajouts de tableaux et modification des commentaires en conséquence.

## 17/11/2025

-   ⚙️ calcul de la correction revenu mixte hybride pour les autres pays que la France.
-   📥Mise à jour des données.
-   🎆 [présentation au séminaire lunch de l'OFCE](seminaire_lunch_OFCE.html).

## 12/11/2025

-   🖌️ 🖌️ version 2 du texte.
-   🖌️ Ajout des références à Cette et al 2019, Trésor Eco 2025.
-   ⚙️ correction par le revenu mixte pour la France.

## 4/11/2025

-   🖌️ 🖌️ version modifiée du texte.
-   📥 Mise à jour des données.
-   ⚙️ premiers éléments sur le revenu mixte.
-   🎆 graphique de la semaine.

## 24/10/2025

-   🖌️ version 1 du document de travail 2025-23.
-   📥 Mise à jour des données.
-   🚀 mise en ligne initiale et pdf.

## 29/09/2025

-   🖌️ 🖌️ 🖌️ version préliminaire du document de travail.
-   📥 Mise à jour des données.

## 26/01/2025

-   🖌️ version corrigée de l'article pour économie politique.

## 18/01/2025

-   🖌️ 🖌️ 🖌️ version initiale du texte pour économie politique.
