---
title: "Le partage de la valeur ajoutée"
subtitle: "Séminaire lunch OFCE"
author-footer: "XT"
author:
  - name: "Xavier Timbeau" 
    email: "xavier.timbeau@sciencespo.fr"
    affiliation: OFCE, Sciences Po Paris
    affiliation-url: "http://www.ofce.fr"
    orcid: "0000-0002-6198-5953"
date: 2025-10-15
lang: fr
format: 
  pres-revealjs:
    toc-depth: 1
    embed-resources: true
editor: visual
bibliography: references.bib
---

# Pourquoi ?

## Pourquoi s'intéresser au partage de la valeur ajoutée ?

-   Un problème essentiellement de mesure

-   Une application directe à la question salariale

    -   Quelle marge de manoeuvre pour revaloriser le travail ?

    -   Quel rapport salarial aujourd'hui ?

    -   Quel rendement du capital ?

-   Un principe : la comptabilité nationale fournit une information, comment et jusqu'où l'utiliser ?

    -   Les notions et les méthodes et de la CN sont homogènes d'un pays à l'autre et dans le temps, on peut donc comparer dans l'espace et dans le temps

## La part des salaires est très élevée en France en 2025

```{r}
ofce::init_qmd()
options(ofce.savegraph = FALSE)
g <- load_graphe("index-fig-psal-1")
girafy(g)
```

## Ce résultat contraste avec des résutlats antérieurs

Depuis @cotis2009 le consensus est que le partage de la valeur ajoutée est stable -- après une période particulière où il a été élevé

Récemment @cette2019 et @tresor2025 convergent vers ce diagnostic.
